### PR TITLE
change dependencies

### PR DESCRIPTION
**Pull request by fisasi1610**
Change dependencies to support newer versions of jquery and bootstrap.

### CODE REVIEW

**Comment by renziito** [comment]
+1

**Comment by jnolbertovm** [comment]
+1

**Comment by MiiMiiM2702** [comment]
+1

**Comment by alvaro-ossio19** [comment]
+1

**Comment by xuqingkuang** [comment]
I will have a try today, please just wait.

**Comment by xuqingkuang** [comment]
Update to a newer dependency is not a easy work, newer dependencies may have breaking changes, dependencies must be limit to be able to control, that's why simple >= is not a good idea.

After test I found the jQuery.size() method was dropped in version 3, and newer jQuery seems breaks the control buttons initialization. So I have to make a bigger patch to make sure the compatibility.

Please enjoy the plugin, issues and patches are welcome.

BTW: the plugin is always incompatible with Bootstrap 4.

**Pull request closed without merging**
